# ビルド用テンプレート
# 出力されるPDFサイズ
# print (B5,ご家庭のプリンタ、コンビニコピー) | prepress (同人誌印刷所A4pdf, B5仕上がり) | ebook（余白極小PDF）
paper: prepress 
# 中表紙の有無
cover: 0
# 目次の有無
toc: 1
# 奥付の有無
imprint: 0
# 書籍タイトル
title: 'Flightbooks Sample Book'
# 書籍著者
author: 'ku-suke'
# 印刷所
print_at: 'flightbooks printing'
# 刊行日
first_release_date: '2023/01 初版'
# コピーライト表記
copyright: '&copy; ku-suke'

# ソースディレクトリ
src_dir: book

# ビルド対象ファイル
chapters:
  - "01.md"
  - "02.md"
  - "03.md"

# はじめにとおわりに(mdファイル名またはnull)
introduction: null
conclusion: null
