# ビルド用テンプレート
# 出力されるPDFサイズ
# JIS-B5 | A5 block_style.ejs#L251参照
paper: JIS-B5 
# 中表紙の有無
cover: 1
# 目次の有無
toc: 1
# 奥付の有無
imprint: 1
# 書籍タイトル
title: 'Flightbooks Sample Book'
# 書籍著者
author: 'ku-suke'
# 印刷所
print_at: 'flightbooks printing'
# 刊行日
first_release_date: '2023/01 初版'
# コピーライト表記
copyright: '© ku-suke'

# ソースディレクトリ
src_dir: book

# ビルド対象ファイル
chapters:
  - "01.md"
  - "02.md"
  - "03.md"

# はじめにとおわりに(mdファイル名またはnull)
introduction: introduction.md
conclusion: conclusion.md
